### ISSUE TITLE
how to update plugins?

### ISSUE THREAD

**Issue by katmratliff** [csdms/pymt#101]
If I want to update a plugin (e.g., rafem), where do I push those changes? I found a Python 2/3 compatibility error. I'd also like to update some of the input file defaults but am not sure where that's best done. Thanks!

**Comment by mcflugen** [comment]
@katmratliff I think the best thing to do would be for you to push your changes to your *rafem* repository. We'll then build a new version of *rafem* and bring them into *pymt*. So long as your changes don't change *rafem*'s *bmi*, it shouldn't be too hard for us to update.

**Comment by katmratliff** [comment]
@mcflugen awesome, thanks! and if I want to update some of the default input values, I can fork and submit a PR to [pymt-rafem repo](https://github.com/pymt-lab/pymt_rafem/tree/master/pymt_rafem)?

**Comment by mdpiper** [comment]
@katmratliff Yup, forking [pymt_rafem](https://github.com/pymt-lab/pymt_rafem) and sending back a PR is the way to go.

(I'm trying to help cover for @mcflugen since he's in New Zealand (!) for a couple weeks.)

**Comment by katmratliff** [comment]
@mdpiper thanks!! Wow, I'm jealous of @mcflugen!
