### ISSUE TITLE
Testing National Water Model Notebooks

### ISSUE THREAD

**Issue by ChristinaB** [csdms/pymt#109]
@gantian127  Do you want me to direct people to give feedback comments here?    This is SO great!

- [ ] The Notebook ran as expected from Binder. Yeah!

- [ ] The kernel crashed within 10 minutes, so limit recommended use to exploring usability, and then give directions to a more stable JupyterHub server. CSDMS? or CUAHSI? 

- [ ] There are no citations or references so when I save a copy, I don't have any provenance information to carry along manually or automated.  

- [ ] If this is in a testing mode, perhaps add a hyperlink to this issue to direct people how you want to collect information. Or give a Google form or any kind of user feedback instructions.

- [ ] My other comments are related to extending the use for COVID-19 seasonality. That would require making local custom versions of the notebooks for local health department or school-sheds linked to the COMID.   Also would require creating historical parameters for seasonality of temperature and relative humidity as the target variables of interest.

**Comment by gantian127** [comment]
@ChristinaB Thanks a lot for your helpful feedback! Since the nwm has its own github repository, it would be better to move this issue there https://github.com/gantian127/nwm. 

I will close this issue and please refer the same issue at https://github.com/gantian127/nwm/issues/5. Thank you!
