### ISSUE TITLE
CSDMS Workbench

### ISSUE THREAD

**Issue by gregtucker** [csdms/pymt#121]
In the recent past, we've sometimes used the name "CSDMS Workbench" to refer collectively to the various modeling tools and protocols (pymt, BMI, babelizer, Landlab, etc.). If this is to be the official name, it should appear prominently in our web portal, repositories, and documentation.

**Comment by mdpiper** [comment]
We could add a "CSDMS Workbench" entry under the "Products" heading on the CSDMS wiki. Each of the doc sets would link to this page. For example, the opening paragraph of the pymt docs could read:

> pymt is the Python Modeling Toolkit. It is an Open Source Python package, developed by the Community Surface Dynamics Modeling System (CSDMS), that provides the tools needed for coupling models that expose the Basic Model Interface (BMI). pymt is part of the CSDMS Workbench. *(<-- add link here)*

Each of the repos could have similar verbiage + link.

**Comment by mdpiper** [comment]
There's now a wiki page for the Workbench: https://csdms.colorado.edu/wiki/Workbench.

**Comment by gregtucker** [comment]
+1

**Comment by mdpiper** [comment]
Added text on the CSDMS Workbench to the BMI, babelizer, pymt, and Standard Names repos, in both READMEs and docs.
